---
- name: Include vars for specific OS version
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install development packages necessary for building Ruby
  package:
    name: "{{ rbenv_packages }}"
    state: present
  become: true

- import_tasks: install.yml
  become: true
  become_user: "{{ rbenv_owner }}"
