---
- name: Converge
  hosts: all
  become: true

  vars:
    rbenv_ruby_versions:
      - 2.7.1

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: rbenv

  post_tasks:
    - name: Verify ruby is installed
      shell:
        cmd: |
          rbenv version | grep 2.7.1
      changed_when: false
